### ISSUE TITLE
Requirement.txt file | Not working

### ISSUE THREAD

**Issue by Ankit-Kulkarni** [swati-jaiswal/Downloader#1]
Here are the details of the error got on 
OS- Ubuntu 12.04 64 bit 
Command -
>> pip install Requirements.txt 

output -
```
Downloading/unpacking Requirements.txt
  Real name of requirement Requirements.txt is requirements-txt
  Could not find any downloads that satisfy the requirement Requirements.txt
No distributions at all found for Requirements.txt
Storing complete log in /home/automata/.pip/pip.log
```
The content of the log file is as follows - 

```
/usr/local/bin/pip run on Tue Dec 23 01:49:11 2014
Downloading/unpacking Requirements.txt
  Getting page http://pypi.python.org/simple/Requirements.txt
  Could not fetch URL http://pypi.python.org/simple/Requirements.txt: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/Requirements.txt when looking for download links for Requirements.txt
  Getting page http://pypi.python.org/simple/
  Real name of requirement Requirements.txt is requirements-txt
  URLs to search for versions for Requirements.txt:
  * http://pypi.python.org/simple/requirements-txt/
  Getting page http://pypi.python.org/simple/requirements-txt/
  Analyzing links from page https://pypi.python.org/simple/requirements-txt/
    Skipping link https://pypi.python.org/packages/source/r/requirements_txt/requirements_txt-0.0.1.tar.gz#md5=7a89c732ef2a6717f73f0917caadd3c9 (from https://pypi.python.org/simple/requirements-txt/); wrong project name (not requirements.txt)
  Could not find any downloads that satisfy the requirement Requirements.txt
No distributions at all found for Requirements.txt
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 948, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 152, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for Requirements.txt

```

Find the attached snapshot below. 
![downloader issue1](https://cloud.githubusercontent.com/assets/2667270/5530504/9714f890-8a46-11e4-96e4-e0615afcbc04.png)

**Comment by swati-jaiswal** [comment]
The problem was with the name of file, it is updated and working now. If you are using python 2, please see the readme instructions for [dependencies][].
[dependencies]: https://github.com/swati-jaiswal/Downloader#dependencies

**Comment by Ankit-Kulkarni** [comment]
Still getting an error message `Real name of requirement requirements.txt
is requirements-txt `, ` Could not find any downloads that satisfy the
requirement requirements.txt`. Renaming file to requirements-txt will do
the work.
`


==========
Ankit Kulkarni (http://ankit-kulkarni.github.io/aboutme/)

**Comment by swati-jaiswal** [comment]
Renamed the file.
